### ISSUE TITLE
Doesn't work with rails 7.0.4 with Tailwind

### ISSUE THREAD

**Issue by kladaFOX** [stimulus-components/stimulus-carousel#10]
Hey maybe you have some thoughts about how to force to work this component with the 7th rails on tailwind.
Because if you just follow the instructions it doesn't work. I also using importmap

**Comment by MarcManiez** [comment]
I'm noticing a similar issue. I followed the instruction in the docs. The erb I have looks like this:

```erb
<div data-controller="carousel" class="swiper-container">
  <div class="swiper-wrapper">
    <div class="swiper-slide">
      <div>something very simple 1</div>
    </div>
    <div class="swiper-slide">
      <div>something very simple 2</div>
    </div>
    <div class="swiper-slide">
      <div>something very simple 3</div>
    </div>
  </div>
</div>
```
I can tell the component is connected because inspecting the HTML reveals all kinds of classes that have been added by the underlying library, such as `swiper-slide-active` or `swiper-slide-next`, but the page seems unchanged: no arrows, and sign of any carousel.

The console is silent, same for `./bin/dev` output.

I'm using rails 7.0.4, tailwind 3.2.2 (although I don't know that tailwind is interfering in any way).

Thank you for any help you're able to provide!

**Comment by MarcManiez** [comment]
On second thought, I think @kladaFOX's hypothesis makes sense.

Looking at the product of the CSS bundle, it's either showing the contents of the CSS for the app as a whole (basically tailwind, in our case), or the CSS for the libraries, but not both at the same time. There's a conflict. This can probably be resolved by tweaking the bundler's configuration, but it's tricky either way. Some documentation would be useful.

I'll update here when I learn how to do it with esbuild.

**Comment by MarcManiez** [comment]
My workaround so far has been to rename the tailwind bundle, and add an import inside `application.html.erb`:

```erb
<%= stylesheet_link_tag "[your_bundle_name]", "data-turbo-track": "reload" %>
```

**Comment by iainbeeston** [comment]
I've found this too. My solution is to import the swiper css from a CDN in my `application.tailwind.css`, like this: `@import url('https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css');` (note that it uses swiper version 8 because at the moment that's what stimulus-carousel uses). Better would be to import it from the swiper package in `node_modules` but I'm not familiar enough with tailwind to know how to import that from tailwind)

**Comment by guillaumebriday** [comment]
If it's still an issue, please reopen it in the main repo: https://github.com/stimulus-components/stimulus-components
